Document: bitcoinwifi
Title: Debian bitcoinwifi Manual
Author: <insert document author here>
Abstract: This manual describes what bitcoinwifi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bitcoinwifi/bitcoinwifi.sgml.gz

Format: postscript
Files: /usr/share/doc/bitcoinwifi/bitcoinwifi.ps.gz

Format: text
Files: /usr/share/doc/bitcoinwifi/bitcoinwifi.text.gz

Format: HTML
Index: /usr/share/doc/bitcoinwifi/html/index.html
Files: /usr/share/doc/bitcoinwifi/html/*.html
